"""Domain analysis: activation junctions, protease diagnostics, coverage,
SILAC labelling, and N-terminomics capture.

All functions are pure over (Entry, parameters) and return plain dicts/lists so
the Streamlit layer can turn them into DataFrames without domain logic leaking
into the UI.

Coordinates everywhere are 1-based inclusive, matching UniProt and proteases.py.
"""

from dataclasses import dataclass

from proteases import PROTEASES, Protease, cleavage_sites, digest, Peptide

# Default SILAC scheme: heavy Lys (+8.0142) and Arg (+10.0083). Only the residue
# set matters for "is this peptide quantifiable"; masses are carried for display.
DEFAULT_SILAC = {"K": 8.0142, "R": 10.0083}

# Amino acids that can actually be used as metabolic (SILAC) labels: the essential
# amino acids (cells cannot synthesise them de novo, so incorporation is complete),
# plus Arg. Non-essential residues are excluded because in-cell synthesis dilutes
# the label. These are the only candidates worth "optimising over".
LABELABLE_AA = ["R", "K", "L", "I", "V", "F", "M", "H", "T", "W"]
AA_NAMES = {
    "R": "Arg", "K": "Lys", "L": "Leu", "I": "Ile", "V": "Val", "F": "Phe",
    "M": "Met", "H": "His", "T": "Thr", "W": "Trp", "Y": "Tyr",
}


# --- Activation junctions ------------------------------------------------------


@dataclass
class Junction:
    pos: int           # J: the processing bond is between residue J and J+1
    side: str          # 'N' = mature lies to the right; 'C' = mature to the left
    mature_start: int  # first residue of the mature chain
    mature_end: int    # last residue of the mature chain
    chain_desc: str
    adjacent: str      # feature on the propeptide side: PROPEP / SIGNAL / TRANSIT / none
    adj_desc: str

    @property
    def is_propeptide(self) -> bool:
        return self.adjacent == "PROPEP"


def find_junctions(entry) -> list[Junction]:
    """Identify processing junctions where a mature chain abuts a propeptide (or
    signal/transit peptide).

    Two geometries are detected:
      * N-terminal removal  — a chain whose start-1 is the end of a propeptide/
        signal/transit peptide (mature lies to the right; neo-N-terminus at start).
      * C-terminal removal  — a chain whose end+1 is the start of a propeptide
        (mature lies to the left; e.g. legumain, proteasome beta subunits).

    Junctions are flagged so the caller knows which are true propeptide-activation
    events (`is_propeptide`) and which side the mature chain is on.
    """
    features = entry.features
    n = entry.length
    by_key: dict = {}

    def consider(cand: Junction):
        key = (cand.pos, cand.side)
        cur = by_key.get(key)
        if (cur is None
                or (cand.is_propeptide and not cur.is_propeptide)
                or (cand.is_propeptide == cur.is_propeptide
                    and (cand.mature_end - cand.mature_start)
                        > (cur.mature_end - cur.mature_start))):
            by_key[key] = cand

    for chain in entry.of_kind("CHAIN"):
        # N-terminal processing bond (chain begins after another feature).
        if chain.start > 1:
            j = chain.start - 1
            adj, desc = "none", ""
            for f in features:
                if f.kind in ("PROPEP", "SIGNAL", "TRANSIT") and f.end == j:
                    adj, desc = f.kind, f.description
                    if f.kind == "PROPEP":
                        break
            # Skip bare initiator-methionine removal (chain starts at residue 2 with
            # nothing annotated before it) — not an activation event.
            if not (j == 1 and adj == "none"):
                consider(Junction(j, "N", chain.start, chain.end,
                                  chain.description, adj, desc))
        # C-terminal processing bond (a propeptide begins right after the chain).
        if chain.end < n:
            j = chain.end
            for f in features:
                if f.kind == "PROPEP" and f.start == j + 1:
                    consider(Junction(j, "C", chain.start, chain.end,
                                      chain.description, "PROPEP", f.description))
                    break

    return [by_key[k] for k in sorted(by_key)]


# --- Protease diagnostics ------------------------------------------------------


def _mature_terminus_peptide(seq: str, protease: Protease, jn: "Junction"):
    """The semi-specific peptide at the mature neo-terminus generated by removal
    of the propeptide, running to the first enzymatic cut site inside the chain.

    N-side: mature N-terminus (J+1) -> first cut site downstream.
    C-side: last cut site upstream -> mature C-terminus (J).
    Returns (start, end, seq).
    """
    sites = cleavage_sites(seq, protease)
    j = jn.pos
    if jn.side == "N":
        start = j + 1
        downstream = [s for s in sites if s > j]
        end = downstream[0] if downstream else len(seq)
    else:  # 'C' — mature ends at J
        end = j
        upstream = [s for s in sites if s < j]
        start = (upstream[-1] + 1) if upstream else 1
    return start, end, seq[start - 1:end]


def junction_diagnostics(entry, protease, missed_cleavages=2, min_len=7, max_len=40):
    """For each junction, decide whether the protease can report activation.

    Returns a list of row dicts (one per junction), including a status and a
    numeric score for ranking proteases.
    """
    if isinstance(protease, str):
        protease = PROTEASES[protease]
    seq = entry.sequence
    peptides = digest(seq, protease, missed_cleavages, min_len, max_len)
    sites = set(cleavage_sites(seq, protease))

    rows = []
    for jn in find_junctions(entry):
        j = jn.pos
        # Peptides spanning the pro/mature bond and within the detectable window.
        spanning = [p for p in peptides if p.spans_bond(j)]
        spanning.sort(key=lambda p: (p.missed, p.length))
        best = spanning[0] if spanning else None
        cuts_at_junction = j in sites

        # Mature neo-terminal (semi-specific) peptide, on the correct side.
        m_start, m_end, m_seq = _mature_terminus_peptide(seq, protease, jn)
        m_len = m_end - m_start + 1
        m_detectable = min_len <= m_len <= max_len

        # A spanning peptide is only *reliably* diagnostic when the junction is
        # NOT an enzymatic cut site. If the enzyme cuts exactly at the junction,
        # the fully-cleaved mature terminal peptide is identical whether or not
        # the propeptide was ever present (the ambiguity case) — the only spanning
        # peptide then requires a missed cleavage at the junction and is
        # unreliable, so we down-rank it rather than call it diagnostic.
        best_bonus = 1 if m_detectable else 0
        if cuts_at_junction:
            if best is not None:
                status = "Ambiguous - spans only via a missed-cleavage peptide"
                score = 1 + best_bonus
            else:
                status = "Ambiguous (cuts exactly at junction)"
                score = 0 + best_bonus
        else:
            if best is not None:
                status = "Diagnostic (fully-specific pro-form peptide)"
                score = 3 + best_bonus
            else:
                status = "No detectable spanning peptide"
                score = 1 + best_bonus

        rows.append({
            "accession": entry.accession,
            "name": entry.name,
            "protease": protease.name,
            "junction": f"{j}|{j + 1}",
            "side": jn.side,
            "mature_start": jn.mature_start,
            "adjacent": jn.adjacent,
            "is_propeptide_junction": jn.is_propeptide,
            "status": status,
            "score": score,
            "cuts_at_junction": cuts_at_junction,
            "spanning_peptide": best.seq if best else "",
            "spanning_start": best.start if best else None,
            "spanning_end": best.end if best else None,
            "spanning_len": best.length if best else None,
            "spanning_missed": best.missed if best else None,
            "mature_term_peptide": m_seq,
            "mature_term_len": m_len,
            "mature_term_detectable": m_detectable,
        })
    return rows


def rank_proteases(entry, protease_names, missed_cleavages=2, min_len=7, max_len=40):
    """Best score per (junction, protease). Returns rows for all combos, and a
    per-junction 'best protease' summary."""
    all_rows = []
    for name in protease_names:
        all_rows.extend(
            junction_diagnostics(entry, name, missed_cleavages, min_len, max_len)
        )
    # Best protease per junction.
    best_by_junction = {}
    for r in all_rows:
        key = (r["junction"], r["side"])
        cur = best_by_junction.get(key)
        if cur is None or r["score"] > cur["score"]:
            best_by_junction[key] = r
    return all_rows, list(best_by_junction.values())


# --- Coverage ------------------------------------------------------------------


def coverage(entry, protease, missed_cleavages=2, min_len=7, max_len=40, region="full"):
    """Sequence coverage by detectable peptides.

    region: 'full' = whole precursor; 'chain' = restrict denominator to mature
    chain residues only. Returns dict with percent and per-residue covered flags.
    """
    if isinstance(protease, str):
        protease = PROTEASES[protease]
    seq = entry.sequence
    n = len(seq)
    peptides = digest(seq, protease, missed_cleavages, min_len, max_len)

    covered = bytearray(n)  # 0/1 per residue (0-based)
    for p in peptides:
        for i in range(p.start - 1, p.end):
            covered[i] = 1

    if region == "chain":
        denom_positions = set()
        for ch in entry.of_kind("CHAIN"):
            denom_positions.update(range(ch.start - 1, ch.end))
        if not denom_positions:
            denom_positions = set(range(n))
    else:
        denom_positions = set(range(n))

    denom = len(denom_positions)
    hit = sum(1 for i in denom_positions if covered[i])
    pct = 100.0 * hit / denom if denom else 0.0
    return {
        "accession": entry.accession,
        "name": entry.name,
        "protease": protease.name,
        "percent": pct,
        "covered_residues": hit,
        "total_residues": denom,
        "covered_flags": bytes(covered),   # length n, 1 where covered
        "cut_sites": cleavage_sites(seq, protease),
        "n_peptides": len(peptides),
    }


# --- SILAC ---------------------------------------------------------------------


def silac_count(pep_seq: str, label_residues=("K", "R")) -> int:
    return sum(pep_seq.upper().count(r) for r in label_residues)


def silac_annotate(peptides, label_residues=("K", "R"), silac_masses=None):
    """Annotate a list of Peptide objects (or (seq,) strings) with label counts."""
    silac_masses = silac_masses or DEFAULT_SILAC
    rows = []
    for p in peptides:
        seq = p.seq if isinstance(p, Peptide) else str(p)
        n_label = silac_count(seq, label_residues)
        heavy_shift = sum(
            seq.upper().count(r) * silac_masses.get(r, 0.0) for r in label_residues
        )
        row = {
            "peptide": seq,
            "length": len(seq),
            "label_sites": n_label,
            "quantifiable": n_label >= 1,
            "heavy_delta_Da": round(heavy_shift, 4),
        }
        if isinstance(p, Peptide):
            row["start"] = p.start
            row["end"] = p.end
            row["missed"] = p.missed
        rows.append(row)
    return rows


def diagnostic_silac(entry, protease, missed_cleavages, min_len, max_len,
                     label_residues=("K", "R"), silac_masses=None):
    """SILAC quantifiability of the diagnostic peptides for each junction:
    the pro-form spanning peptide and the mature neo-N-terminal peptide."""
    diag = junction_diagnostics(entry, protease, missed_cleavages, min_len, max_len)
    rows = []
    for d in diag:
        term_label = "mature N-term" if d["side"] == "N" else "mature C-term"
        for kind, seq in (("pro-form spanning", d["spanning_peptide"]),
                          (term_label, d["mature_term_peptide"])):
            if not seq:
                continue
            n_label = silac_count(seq, label_residues)
            rows.append({
                "accession": d["accession"],
                "name": d["name"],
                "protease": d["protease"],
                "junction": d["junction"],
                "peptide_role": kind,
                "peptide": seq,
                "length": len(seq),
                "label_sites": n_label,
                "quantifiable": n_label >= 1,
            })
    return rows


# --- N-terminomics -------------------------------------------------------------


def nterminomics_capture(entry, protease, missed_cleavages=2, min_len=7, max_len=40):
    """Which mature neo-N-termini (from propeptide/signal removal) would be
    captured as detectable N-terminal peptides.

    In an N-terminomics workflow (e.g. TAILS / reductive dimethylation), protein
    N-termini are blocked and internal tryptic peptides depleted; the peptide you
    recover from a processed protein runs from the mature N-terminus to the first
    enzymatic cut site. Its detection reports the activation event directly.
    """
    if isinstance(protease, str):
        protease = PROTEASES[protease]
    seq = entry.sequence
    rows = []
    for jn in find_junctions(entry):
        if jn.side != "N":
            continue  # N-terminomics captures N-termini only (C-side needs C-TAILS)
        m_start, m_end, m_seq = _mature_terminus_peptide(seq, protease, jn)
        m_len = m_end - m_start + 1
        rows.append({
            "accession": entry.accession,
            "name": entry.name,
            "protease": protease.name,
            "neo_nterm_pos": jn.mature_start,
            "adjacent": jn.adjacent,
            "is_propeptide_junction": jn.is_propeptide,
            "captured_peptide": m_seq,
            "start": m_start,
            "end": m_end,
            "length": m_len,
            "detectable": min_len <= m_len <= max_len,
        })
    return rows


# --- Aggregate protease scorecard ---------------------------------------------


def protease_scorecard(entries, protease_names, missed_cleavages=2,
                       min_len=7, max_len=40, propeptide_only=True):
    """Aggregate result across the whole queried set: for each protease, how many
    activation junctions it can diagnose ("Trypsin: X of Y diagnostic").

    Counts a junction once per protein/junction (not per protease-row). Returns a
    list of dict rows sorted best-first.
    """
    # Total junctions in scope (constant across proteases).
    scope = []
    for e in entries:
        for jn in find_junctions(e):
            if propeptide_only and not jn.is_propeptide:
                continue
            scope.append((e.accession, f"{jn.pos}|{jn.pos + 1}", jn.side))
    total = len(scope)

    rows = []
    for name in protease_names:
        diagnostic = ambiguous = no_span = nterm_ok = 0
        for e in entries:
            for d in junction_diagnostics(e, name, missed_cleavages, min_len, max_len):
                if propeptide_only and not d["is_propeptide_junction"]:
                    continue
                if d["status"].startswith("Diagnostic"):
                    diagnostic += 1
                elif d["status"].startswith("Ambiguous"):
                    ambiguous += 1
                else:
                    no_span += 1
                if d["side"] == "N" and d["mature_term_detectable"]:
                    nterm_ok += 1
        rows.append({
            "protease": name,
            "diagnostic": diagnostic,
            "ambiguous": ambiguous,
            "no_spanning_pep": no_span,
            "total_junctions": total,
            "pct_diagnostic": round(100.0 * diagnostic / total, 1) if total else 0.0,
            "nterm_detectable": nterm_ok,
        })
    rows.sort(key=lambda r: (r["diagnostic"], r["nterm_detectable"]), reverse=True)
    return rows


# --- SILAC label optimisation --------------------------------------------------


def diagnostic_peptides(entry, protease, missed_cleavages=2, min_len=7, max_len=40,
                        propeptide_only=True):
    """The peptides that report activation at each junction: the pro-form spanning
    peptide (present in the pro-form) and the mature neo-terminal peptide (present
    after activation). Returns list of dict rows."""
    out = []
    for d in junction_diagnostics(entry, protease, missed_cleavages, min_len, max_len):
        if propeptide_only and not d["is_propeptide_junction"]:
            continue
        term_role = "mature N-term" if d["side"] == "N" else "mature C-term"
        if d["spanning_peptide"]:
            out.append({"accession": entry.accession, "junction": d["junction"],
                        "role": "pro-form spanning", "peptide": d["spanning_peptide"]})
        if d["mature_term_peptide"]:
            out.append({"accession": entry.accession, "junction": d["junction"],
                        "role": term_role, "peptide": d["mature_term_peptide"]})
    return out


def _label_display(token: str) -> str:
    aas = list(token.upper())
    return "+".join(AA_NAMES.get(a, a) for a in aas)


def silac_label_optimization(entries, protease, missed_cleavages=2, min_len=7,
                             max_len=40, candidates=None, propeptide_only=True):
    """Which label best covers a protease's diagnostic peptides.

    Each candidate is one or more labelable residues (e.g. "K", "L", or "KR" for
    the standard Lys+Arg SILAC pair — a peptide counts if it contains ANY of them).
    Reports how many diagnostic peptides across the queried set would carry >=1
    heavy residue (become SILAC-quantifiable). Ranked best-first; the top row is
    the optimal label. A single internal residue can out-score K or R alone,
    because a tryptic peptide ends in only one of K/R — which is exactly why the
    standard "KR" pair exists.
    """
    candidates = candidates or (["KR"] + LABELABLE_AA)
    peps = []
    for e in entries:
        peps.extend(diagnostic_peptides(e, protease, missed_cleavages, min_len,
                                        max_len, propeptide_only))
    total = len(peps)
    rows = []
    for token in candidates:
        residues = set(token.upper())
        counts = [sum(p["peptide"].upper().count(a) for a in residues) for p in peps]
        quant = sum(1 for c in counts if c >= 1)
        aa_key = "+".join(sorted(residues))
        rows.append({
            "amino_acid": f"{aa_key} ({_label_display(token)})",
            "aa": aa_key,
            "quantifiable": quant,
            "total_peptides": total,
            "pct_quantifiable": round(100.0 * quant / total, 1) if total else 0.0,
            "avg_labels_per_pep": round(sum(counts) / total, 2) if total else 0.0,
            "min_labels": min(counts) if counts else 0,
        })
    rows.sort(key=lambda r: (r["quantifiable"], r["avg_labels_per_pep"]), reverse=True)
    return rows
